(function () {
  const $ = (sel, root = document) => root.querySelector(sel);
  const DAYS = ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"];
  const DEFAULT_CODES = {5:"حصة5",6:"حصة6",7:"حصة7",8:"حصة8",9:"حصة9",10:"حصة10",11:"حصة11",12:"حصة12"};
  const state = {db:null,firebaseReady:false,isTeacher:sessionStorage.getItem("math_teacher")==="1",studentGrade:sessionStorage.getItem("math_student_grade")||"",filterGrade:"all",classes:[],codes:{...DEFAULT_CODES}};
  function isConfigured(){const c=window.FIREBASE_CONFIG||{};return c.apiKey&&!String(c.apiKey).includes("PASTE_YOUR");}
  function initFirebase(){const pill=$("#fbStatus");if(!isConfigured()){pill.innerHTML="<i></i> وضع تجريبي";return;}try{firebase.initializeApp(window.FIREBASE_CONFIG);state.db=firebase.firestore();state.firebaseReady=true;pill.classList.add("live");pill.innerHTML="<i></i> متصل بـ Firebase";}catch(err){pill.innerHTML="<i></i> تعذر الاتصال";}}
  function escapeHtml(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">",'"':""","'":"&#39;"}[c]));}
  function formatTime(t){if(!t)return"";const [h,m]=String(t).split(":");const n=Number(h);const suffix=n<12?"ص":"م";const hour=((n+11)%12)+1;return `${hour}:${m||"00"} ${suffix}`;}
  function canSeeSchedule(){return state.isTeacher||!!state.studentGrade;}
  function updateAccessUI(){const open=canSeeSchedule();if(state.isTeacher)$("#studentGate")?.classList.add("hidden");else $("#studentGate")?.classList.toggle("hidden",open);$("#afterLoginCta")?.classList.toggle("hidden",!open||state.isTeacher);$("#gradesSection")?.classList.toggle("hidden",!open);$("#scheduleSection")?.classList.toggle("hidden",!open);$("#teacherBar").classList.toggle("hidden",!state.isTeacher);$("#btnTeacher").classList.toggle("hidden",state.isTeacher);$("#btnAddClass")?.classList.toggle("hidden",!state.isTeacher);$("#teacherScheduleHint")?.classList.toggle("hidden",!state.isTeacher);$("#btnAllGrades")?.classList.toggle("hidden",!state.isTeacher);if(state.studentGrade&&!state.isTeacher)state.filterGrade=state.studentGrade;}
  async function loadCodes(){try{if(state.firebaseReady){const snap=await state.db.collection("studentCodes").get();if(!snap.empty)snap.docs.forEach(d=>{if(d.data().code)state.codes[d.id]=String(d.data().code);});}else{const local=JSON.parse(localStorage.getItem("math_student_codes")||"null");if(local)state.codes={...DEFAULT_CODES,...local};}}catch(err){const local=JSON.parse(localStorage.getItem("math_student_codes")||"null");if(local)state.codes={...DEFAULT_CODES,...local};}renderCodesEditor();}
  function renderCodesEditor(){const host=$("#codesEditor");if(!host)return;host.innerHTML=Object.keys(window.PORTAL_CONTENT).map(g=>`<div class=\"code-row\"><label>${window.PORTAL_CONTENT[g].title}</label><input data-grade=\"${g}\" class=\"code-input\" value=\"${escapeHtml(state.codes[g]||\"\")}\" /></div>`).join("");}
  async function saveCodes(){const msg=$("#codesMsg");const next={...state.codes};document.querySelectorAll(".code-input").forEach(inp=>{next[inp.getAttribute("data-grade")]=inp.value.trim();});try{if(state.firebaseReady){const batch=state.db.batch();Object.keys(next).forEach(g=>batch.set(state.db.collection("studentCodes").doc(g),{code:next[g]}));await batch.commit();}else localStorage.setItem("math_student_codes",JSON.stringify(next));state.codes=next;msg.className="msg ok";msg.textContent="تم حفظ الرموز.";}catch(err){msg.className="msg err";msg.textContent="تعذر حفظ الرموز.";}}
  function studentEnter(){const raw=($("#studentCode")?.value||"").trim();const msg=$("#studentMsg");if(!raw){msg.className="msg err";msg.textContent="أدخل الرمز الذي أعطاك المعلم.";return;}const found=Object.keys(state.codes).find(g=>String(state.codes[g])===raw);if(!found){msg.className="msg err";msg.textContent="الرمز غير صحيح.";return;}state.studentGrade=found;state.filterGrade=found;sessionStorage.setItem("math_student_grade",found);msg.className="msg ok";msg.textContent="تم الدخول إلى حصص "+window.PORTAL_CONTENT[found].title;updateAccessUI();renderHomeGrades();updateScheduleHead();renderWeekGrid();setTimeout(()=>$("#scheduleSection").scrollIntoView({behavior:"smooth"}),200);}
  function studentOut(){sessionStorage.removeItem("math_student_grade");state.studentGrade="";state.filterGrade="all";if($("#studentCode"))$("#studentCode").value="";if($("#studentMsg"))$("#studentMsg").textContent="";updateAccessUI();renderHomeGrades();updateScheduleHead();renderWeekGrid();window.scrollTo({top:0,behavior:"smooth"});}
  function renderHomeGrades(){const grid=$("#gradesGrid");if(!grid)return;grid.innerHTML="";const grades=state.isTeacher?Object.keys(window.PORTAL_CONTENT):(state.studentGrade?[state.studentGrade]:[]);grades.forEach(g=>{const data=window.PORTAL_CONTENT[g];const card=document.createElement("article");card.className="grade-card"+(state.filterGrade===g?" selected":"");card.style.setProperty("--accent",data.color);card.innerHTML=`<div class=\"num\">${g}</div><h4>${data.title}</h4><div class=\"go\">حصص هذا الصف</div>`;card.addEventListener("click",()=>{state.filterGrade=g;updateScheduleHead();renderHomeGrades();renderWeekGrid();$("#scheduleSection").scrollIntoView({behavior:"smooth"});});grid.appendChild(card);});}
  function updateScheduleHead(){if(!state.isTeacher&&state.studentGrade){$("#scheduleTitle").textContent="حصص "+window.PORTAL_CONTENT[state.studentGrade].title;$("#scheduleSub").textContent="دخلت برمز المعلم";return;}if(state.filterGrade==="all"){$("#scheduleTitle").textContent="الجدول الأسبوعي";$("#scheduleSub").textContent="كل الصفوف";}else{$("#scheduleTitle").textContent="حصص "+window.PORTAL_CONTENT[state.filterGrade].title;$("#scheduleSub").textContent="حصص هذا الصف";}}
  async function loadClasses(){try{if(state.firebaseReady){const snap=await state.db.collection("weeklyClasses").get();state.classes=snap.docs.map(d=>({id:d.id,...d.data()}));}else state.classes=JSON.parse(localStorage.getItem("math_classes")||"[]");}catch(err){state.classes=JSON.parse(localStorage.getItem("math_classes")||"[]");}renderWeekGrid();}
  function filteredClasses(){const grade=!state.isTeacher&&state.studentGrade?state.studentGrade:state.filterGrade;return state.classes.filter(c=>grade==="all"||String(c.grade)===String(grade)).sort((a,b)=>String(a.start||"").localeCompare(String(b.start||"")));}
  function renderWeekGrid(){const grid=$("#weekGrid");if(!grid)return;const today=new Date().getDay();const items=canSeeSchedule()?filteredClasses():[];grid.innerHTML=DAYS.map((name,day)=>{const list=items.filter(c=>Number(c.day)===day);return `<div class=\"day-col ${day===today?"today":""}\"><h4>${name}${day===today?" · اليوم":""}</h4><div class=\"day-list\">${list.length?list.map(classCardHtml).join(""):`<div class=\"meta\" style=\"color:var(--muted);padding:8px;font-size:.8rem\">لا حصة</div>`}</div></div>`;}).join("");$("#weekEmpty")?.classList.toggle("hidden",items.length>0);grid.querySelectorAll(".del-class").forEach(btn=>btn.addEventListener("click",()=>deleteClass(btn.getAttribute("data-id"))));}
  function classCardHtml(c){const color=(window.PORTAL_CONTENT[c.grade]||{}).color||"#0e8f8a";const gradeName=(window.PORTAL_CONTENT[c.grade]||{}).title||("الصف "+c.grade);return `<article class=\"class-card\" style=\"--accent:${color}\"><div class=\"time\">${formatTime(c.start)}${c.end?" – "+formatTime(c.end):""}</div><div class=\"topic\">${escapeHtml(c.topic||"حصة رياضيات")}</div><div class=\"meta\">${escapeHtml(gradeName)}${c.place?" · "+escapeHtml(c.place):""}</div>${c.notes?`<div class=\"meta\">${escapeHtml(c.notes)}</div>`:""}${state.isTeacher?`<div class=\"row-actions\"><span class=\"meta\">كل أسبوع</span><button class=\"btn-tiny del-class\" data-id=\"${escapeHtml(c.id)}\" type=\"button\">حذف</button></div>`:`<div class=\"meta\">كل أسبوع</div>`}</article>`;}
  function fillGradeSelect(){if(!$("#classGrade"))return;$("#classGrade").innerHTML=Object.keys(window.PORTAL_CONTENT).map(g=>`<option value=\"${g}\">${window.PORTAL_CONTENT[g].title}</option>`).join("");}
  function openClassModal(){if(!state.isTeacher)return openTeacherModal();$("#classMsg").textContent="";if(state.filterGrade!=="all")$("#classGrade").value=state.filterGrade;$("#classModal").classList.remove("hidden");}
  function closeClassModal(){$("#classModal").classList.add("hidden");}
  async function saveClass(){const msg=$("#classMsg");const item={grade:$("#classGrade").value,day:Number($("#classDay").value),start:$("#classStart").value,end:$("#classEnd").value,topic:$("#classTopic").value.trim(),place:$("#classPlace").value.trim(),notes:$("#classNotes").value.trim(),createdAt:Date.now()};if(!item.topic||!item.start){msg.className="msg err";msg.textContent="أدخل الموضوع والوقت.";return;}try{if(state.firebaseReady){const ref=await state.db.collection("weeklyClasses").add({...item,createdAt:firebase.firestore.FieldValue.serverTimestamp()});item.id=ref.id;}else{item.id="local-"+Date.now();const all=JSON.parse(localStorage.getItem("math_classes")||"[]");all.push(item);localStorage.setItem("math_classes",JSON.stringify(all));}state.classes.push(item);msg.className="msg ok";msg.textContent="تم حفظ الحصة.";$("#classTopic").value="";$("#classNotes").value="";renderWeekGrid();setTimeout(closeClassModal,400);}catch(err){msg.className="msg err";msg.textContent="تعذر الحفظ.";}}
  async function deleteClass(id){if(!id||!state.isTeacher)return;if(!confirm("حذف هذه الحصة؟"))return;try{if(state.firebaseReady&&!String(id).startsWith("local-"))await state.db.collection("weeklyClasses").doc(id).delete();else{const all=JSON.parse(localStorage.getItem("math_classes")||"[]").filter(c=>c.id!==id);localStorage.setItem("math_classes",JSON.stringify(all));}state.classes=state.classes.filter(c=>c.id!==id);renderWeekGrid();}catch(err){alert("تعذر الحذف.");}}
  function openTeacherModal(){$("#teacherModal").classList.remove("hidden");$("#teacherCode").focus();}
  function closeTeacherModal(){$("#teacherModal").classList.add("hidden");$("#loginMsg").textContent="";$("#teacherCode").value="";}
  async function loginTeacher(){const code=$("#teacherCode").value.trim();const msg=$("#loginMsg");if(!code){msg.className="msg err";msg.textContent="أدخل الرقم السري.";return;}let ok=false;if(state.firebaseReady){try{const doc=await state.db.collection("settings").doc("teacher").get();if(doc.exists&&String(doc.data().secretCode)===code)ok=true;else{msg.className="msg err";msg.textContent="الرقم غير مطابق.";return;}}catch(err){msg.className="msg err";msg.textContent="خطأ Firebase.";return;}}else if(code===window.FALLBACK_TEACHER_CODE)ok=true;if(!ok){msg.className="msg err";msg.textContent="رقم خاطئ. للتجريب: 123456";return;}sessionStorage.setItem("math_teacher","1");state.isTeacher=true;closeTeacherModal();updateAccessUI();renderCodesEditor();renderHomeGrades();updateScheduleHead();renderWeekGrid();}
  function logoutTeacher(){sessionStorage.removeItem("math_teacher");state.isTeacher=false;updateAccessUI();renderHomeGrades();updateScheduleHead();renderWeekGrid();}
  function bind(){$("#btnTeacher")?.addEventListener("click",openTeacherModal);$("#btnLogout")?.addEventListener("click",logoutTeacher);$("#closeModal")?.addEventListener("click",closeTeacherModal);$("#doLogin")?.addEventListener("click",loginTeacher);$("#teacherCode")?.addEventListener("keydown",e=>{if(e.key==="Enter")loginTeacher();});$("#teacherModal")?.addEventListener("click",e=>{if(e.target.id==="teacherModal")closeTeacherModal();});$("#exploreBtn")?.addEventListener("click",()=>$("#scheduleSection").scrollIntoView({behavior:"smooth"}));$("#btnStudentEnter")?.addEventListener("click",studentEnter);$("#studentCode")?.addEventListener("keydown",e=>{if(e.key==="Enter")studentEnter();});$("#btnStudentOut")?.addEventListener("click",studentOut);$("#btnAddClass")?.addEventListener("click",openClassModal);$("#closeClassModal")?.addEventListener("click",closeClassModal);$("#saveClass")?.addEventListener("click",saveClass);$("#saveCodes")?.addEventListener("click",saveCodes);$("#classModal")?.addEventListener("click",e=>{if(e.target.id==="classModal")closeClassModal();});$("#btnAllGrades")?.addEventListener("click",()=>{if(!state.isTeacher)return;state.filterGrade="all";updateScheduleHead();renderHomeGrades();renderWeekGrid();});$("#brand")?.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));}
  document.addEventListener("DOMContentLoaded",async()=>{initFirebase();fillGradeSelect();bind();await loadCodes();await loadClasses();updateAccessUI();renderHomeGrades();updateScheduleHead();renderWeekGrid();});
})();
